"""Private local Baseline and human-review support."""

from velune_trace.private_baseline.contract import (
    ACTOR_IDENTITY_MAX_LENGTH,
    BASELINE_ID_KIND,
    BASELINE_REVISION_ID_KIND,
    CUSTOM_AXIS_VALUE_MAX_LENGTH,
    DIMENSION_KEY_MAX_LENGTH,
    DIMENSION_VALUE_MAX_LENGTH,
    DISPLAY_NAME_MAX_LENGTH,
    EVALUATION_ID_KIND,
    HUMAN_LABEL_MAX_LENGTH,
    IDENTIFIER_COLLISION_RETRY_LIMIT,
    IDENTIFIER_HEX_LENGTH,
    IDENTIFIER_RANDOM_BYTE_COUNT,
    ID_PREFIX_BY_KIND,
    MARKDOWN_FIELD_DETAIL_LIMIT_PER_TOPIC,
    MARKDOWN_REFERENCE_PREVIEW_LIMIT,
    MARKDOWN_TOPIC_DETAIL_LIMIT,
    MARKDOWN_TOPIC_PREVIEW_LIMIT,
    MAX_DIMENSION_KEYS,
    MULTILINE_NOTE_MAX_LENGTH,
    PRIVATE_BASELINE_JUDGMENT_BOUNDARY,
    PRIVATE_BASELINE_PRESENTATION_POLICY_VERSION,
    PRIVATE_BASELINE_SCHEMA_VERSION,
    PRIVATE_BASELINE_VISIBILITY,
    REFERENCE_MEMBERSHIP_LIMIT,
    REVIEWER_IDENTITY_MAX_LENGTH,
    REVIEW_RECORD_ID_KIND,
    build_private_baseline_judgment_boundary,
    generate_baseline_id_candidate,
    generate_baseline_revision_id_candidate,
    generate_evaluation_id_candidate,
    generate_review_record_id_candidate,
    normalize_dimensions,
    normalize_multiline_note,
    normalize_single_line_text,
    validate_opaque_identifier,
)
from velune_trace.private_baseline.registry import (
    BASELINE_REGISTRY_FILENAME,
    BASELINE_REGISTRY_SCHEMA_NAME,
    BASELINE_REGISTRY_SEMANTICS,
    LoadedPrivateBaselineRegistry,
    LoadedRegistryRecord,
    PrivateBaselineRegistryError,
    load_private_baseline_registry,
)
from velune_trace.private_baseline.revision import (
    BASELINE_REVISION_SCHEMA_NAME,
    BASELINE_REVISION_SEMANTICS,
    ISO8601_TIMESTAMP_MAX_LENGTH,
    MEMBERSHIP_ID_PREFIX,
    MEMBERSHIP_ID_WIDTH,
    REPORT_BUNDLE_ID_PREFIX,
    SHA256_HEX_LENGTH,
    PrivateBaselineRevisionError,
    build_baseline_revision,
    normalize_dimension_policy,
    validate_baseline_revision,
)
from velune_trace.private_baseline.errors import (
    PrivateBaselineContractError,
)

from velune_trace.private_baseline.service import (
    CreatedPrivateBaseline,
    PrivateBaselineServiceError,
    create_private_baseline,
)

__all__ = [
    "CreatedPrivateBaseline",
    "PrivateBaselineServiceError",
    "create_private_baseline",
    "BASELINE_REGISTRY_FILENAME",
    "BASELINE_REGISTRY_SCHEMA_NAME",
    "BASELINE_REGISTRY_SEMANTICS",
    "LoadedPrivateBaselineRegistry",
    "LoadedRegistryRecord",
    "PrivateBaselineRegistryError",
    "load_private_baseline_registry",
    "BASELINE_REVISION_SCHEMA_NAME",
    "BASELINE_REVISION_SEMANTICS",
    "ISO8601_TIMESTAMP_MAX_LENGTH",
    "MEMBERSHIP_ID_PREFIX",
    "MEMBERSHIP_ID_WIDTH",
    "REPORT_BUNDLE_ID_PREFIX",
    "SHA256_HEX_LENGTH",
    "PrivateBaselineRevisionError",
    "build_baseline_revision",
    "normalize_dimension_policy",
    "validate_baseline_revision",
    "ACTOR_IDENTITY_MAX_LENGTH",
    "BASELINE_ID_KIND",
    "BASELINE_REVISION_ID_KIND",
    "CUSTOM_AXIS_VALUE_MAX_LENGTH",
    "DIMENSION_KEY_MAX_LENGTH",
    "DIMENSION_VALUE_MAX_LENGTH",
    "DISPLAY_NAME_MAX_LENGTH",
    "EVALUATION_ID_KIND",
    "HUMAN_LABEL_MAX_LENGTH",
    "IDENTIFIER_COLLISION_RETRY_LIMIT",
    "IDENTIFIER_HEX_LENGTH",
    "IDENTIFIER_RANDOM_BYTE_COUNT",
    "ID_PREFIX_BY_KIND",
    "MARKDOWN_FIELD_DETAIL_LIMIT_PER_TOPIC",
    "MARKDOWN_REFERENCE_PREVIEW_LIMIT",
    "MARKDOWN_TOPIC_DETAIL_LIMIT",
    "MARKDOWN_TOPIC_PREVIEW_LIMIT",
    "MAX_DIMENSION_KEYS",
    "MULTILINE_NOTE_MAX_LENGTH",
    "PRIVATE_BASELINE_JUDGMENT_BOUNDARY",
    "PRIVATE_BASELINE_PRESENTATION_POLICY_VERSION",
    "PRIVATE_BASELINE_SCHEMA_VERSION",
    "PRIVATE_BASELINE_VISIBILITY",
    "PrivateBaselineContractError",
    "REFERENCE_MEMBERSHIP_LIMIT",
    "REVIEWER_IDENTITY_MAX_LENGTH",
    "REVIEW_RECORD_ID_KIND",
    "build_private_baseline_judgment_boundary",
    "generate_baseline_id_candidate",
    "generate_baseline_revision_id_candidate",
    "generate_evaluation_id_candidate",
    "generate_review_record_id_candidate",
    "normalize_dimensions",
    "normalize_multiline_note",
    "normalize_single_line_text",
    "validate_opaque_identifier",
]

from velune_trace.private_baseline.evaluation import (
    EVALUATION_REPORT_FILENAME,
    EVALUATION_SCHEMA_NAME,
    EVALUATION_SEMANTICS,
    EVALUATION_SUMMARY_FILENAME,
    HUMAN_JUDGMENT_BOUNDARY_STATEMENT,
    PrivateBaselineEvaluationError,
    aggregate_reference_comparisons,
    build_private_baseline_evaluation_report,
    normalize_evaluation_context,
)
from velune_trace.private_baseline.evaluation_writer import (
    WrittenPrivateBaselineEvaluation,
    render_private_baseline_evaluation_summary,
    write_private_baseline_evaluation_outputs,
)

__all__ += [
    "EVALUATION_REPORT_FILENAME",
    "EVALUATION_SCHEMA_NAME",
    "EVALUATION_SEMANTICS",
    "EVALUATION_SUMMARY_FILENAME",
    "HUMAN_JUDGMENT_BOUNDARY_STATEMENT",
    "PrivateBaselineEvaluationError",
    "WrittenPrivateBaselineEvaluation",
    "aggregate_reference_comparisons",
    "build_private_baseline_evaluation_report",
    "normalize_evaluation_context",
    "render_private_baseline_evaluation_summary",
    "write_private_baseline_evaluation_outputs",
]

from velune_trace.private_baseline.evaluation_service import (
    EvaluatedPrivateBaseline,
    PrivateBaselineEvaluationServiceError,
    evaluate_private_baseline,
)

__all__ += [
    "EvaluatedPrivateBaseline",
    "PrivateBaselineEvaluationServiceError",
    "evaluate_private_baseline",
]
